[package]
name = "cuda-jit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
log = "0.4.17"
pretty_env_logger = "0.4.0"
